# Generated by Django 3.1.7 on 2021-02-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=124)),
                ('is_completed', models.BooleanField(default=False)),
                ('to_be_completed_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
